import 'package:get/get.dart';

import '../models/wizard_week_models.dart';
import '../services/diet_plan_wizard_service.dart';
import 'wizard_controller.dart';

/// Step 5, v4.0 ('plan-item') mode - the sibling to FinalizeStepController,
/// used instead of it for a DietPlan whose dataModel is 'plan-item' (see
/// wizard_view.dart's routing). Same two-sub-state shape as the original
/// (pre-finalize adjustments, then a post-finalize read-only review), but
/// built around ingredient-level RecipeVersion editing instead of a
/// servingMultiplier:
///
/// 1. Refine Portions (isFinalized == false): every item generated by Step 4
///    is a recipe's V1 (services/menuGenerationService.js never scales).
///    Auto-Balance Day/Week nudges ingredient quantities toward the daily
///    calorie target; tapping a recipe opens the Ingredient Editor
///    (widgets/ingredient_editor_sheet.dart), which creates a V2 and
///    repoints that one PlanItem - siblings are untouched.
/// 2. Finalized (isFinalized == true): read-only detailed review of exactly
///    what will be prescribed - recipe name, exact ingredient list, cooking
///    steps, supplements - before Confirm & Activate.
class PlanItemFinalizeStepController extends GetxController {
  final WizardController wizard = Get.find<WizardController>();
  final DietPlanWizardService wizardService = DietPlanWizardService();

  final RxBool loading = false.obs;
  final RxBool isFinalized = false.obs;
  final RxnString errorMessage = RxnString();
  final RxList<WizardDayGroupV2> weekDays = <WizardDayGroupV2>[].obs;
  final RxBool finalizing = false.obs;
  final RxBool activating = false.obs;
  final RxBool autoBalancingWeek = false.obs;
  final RxSet<String> autoBalancingDayPlanIds = <String>{}.obs;

  String get patientId => wizard.patientId;
  String get dietPlanId => wizard.dietPlanId.value ?? '';
  int get week => wizard.targetWeek.value;

  /// Same source TargetsStepController writes to - a plain per-day calorie
  /// figure, not the per-slot mealDistribution split (auto-balance operates
  /// on a day/week total, see services/ingredientAutoBalanceService.js).
  double? get dailyCalorieTarget =>
      (wizard.patientsController.selectedCalorieStrategy['calorieBudget'] as num?)?.toDouble();

  @override
  void onInit() {
    super.onInit();
    if (dietPlanId.isNotEmpty) loadWeekPlanItems();
  }

  Future<void> loadWeekPlanItems() async {
    loading.value = true;
    errorMessage.value = null;
    try {
      final response = await wizardService.getWeekPlanItems(patientId: patientId, dietPlanId: dietPlanId, week: week);
      if (response == null || response['success'] != true) {
        errorMessage.value = 'Could not load this week\'s plan.';
        return;
      }
      final data = response['data'] as Map<String, dynamic>;
      isFinalized.value = data['workflowStatus'] == 'finalized';
      weekDays.assignAll((data['days'] as List? ?? []).map((d) => WizardDayGroupV2.fromJson(d)).toList());
    } finally {
      loading.value = false;
    }
  }

  Future<bool> editIngredients(WizardPlanItemV2 item, List<WizardIngredientLine> updatedIngredients) async {
    final result = await wizardService.createCustomVersion(
      patientId: patientId,
      dietPlanId: dietPlanId,
      planItemId: item.id,
      ingredients: updatedIngredients.map((i) => i.toJson()).toList(),
    );
    final ok = result != null && result['success'] == true;
    if (ok) await loadWeekPlanItems();
    return ok;
  }

  Future<void> autoBalanceDay(String dayPlanId) async {
    final target = dailyCalorieTarget;
    if (target == null || target <= 0) return;
    autoBalancingDayPlanIds.add(dayPlanId);
    try {
      final result = await wizardService.autoBalanceDay(
        patientId: patientId,
        dietPlanId: dietPlanId,
        dayPlanId: dayPlanId,
        targetDailyCalories: target,
      );
      if (result != null && result['success'] == true) await loadWeekPlanItems();
    } finally {
      autoBalancingDayPlanIds.remove(dayPlanId);
    }
  }

  Future<void> autoBalanceWeek() async {
    final target = dailyCalorieTarget;
    if (target == null || target <= 0) return;
    autoBalancingWeek.value = true;
    try {
      final result = await wizardService.autoBalanceWeek(
        patientId: patientId,
        dietPlanId: dietPlanId,
        week: week,
        targetDailyCalories: target,
      );
      if (result != null && result['success'] == true) await loadWeekPlanItems();
    } finally {
      autoBalancingWeek.value = false;
    }
  }

  Future<void> swapRecipe(WizardPlanItemV2 item, String newParentRecipeId) async {
    final result = await wizardService.swapRecipeVersion(
      patientId: patientId,
      dietPlanId: dietPlanId,
      planItemId: item.id,
      newParentRecipeId: newParentRecipeId,
    );
    if (result != null && result['success'] == true) await loadWeekPlanItems();
  }

  Future<bool> finalizeThisWeek() async {
    finalizing.value = true;
    errorMessage.value = null;
    try {
      final response = await wizardService.finalizePlanItemWeek(patientId: patientId, dietPlanId: dietPlanId);
      if (response == null || response['success'] != true) {
        errorMessage.value = response?['message']?.toString() ?? 'Finalize failed.';
        return false;
      }
      isFinalized.value = true;
      await loadWeekPlanItems();
      return true;
    } finally {
      finalizing.value = false;
    }
  }

  Future<bool> activatePlan() async {
    activating.value = true;
    try {
      await wizard.patientsController.activateDietPlan(patientId, dietPlanId);
      return true;
    } finally {
      activating.value = false;
    }
  }
}
