import 'package:docwellnesdoc/app/modules/receipes/models/recipe_model.dart';
import 'package:docwellnesdoc/app/utils/common_widgets/app_toast.dart';
import 'package:get/get.dart';

import '../models/wizard_week_models.dart';
import '../services/diet_plan_wizard_service.dart';
import 'wizard_controller.dart';

/// Step 3 (Refine Portions), new-plan-item-flow only - see
/// WizardController.isNewPlanFlow's doc comment for why this is a distinct
/// step from Finalize now, matching the v4.0 spec's literal order, rather
/// than a pre-finalize sub-state living inside the Finalize step (the
/// earlier design this replaces).
///
/// Every item generated by Step 2 is a recipe's V1
/// (services/menuGenerationService.js never scales). The week is
/// automatically auto-balanced toward the daily calorie target exactly once
/// when this step first loads (see onInit/_autoBalancedOnce below) - there
/// is no manual "Auto-Balance" action anymore. Tapping a recipe opens the
/// Ingredient Editor (widgets/ingredient_editor_sheet.dart), which creates a
/// V2 and repoints that one PlanItem - siblings are untouched.
class RefinePortionsStepController extends GetxController {
  final WizardController wizard = Get.find<WizardController>();
  final DietPlanWizardService wizardService = DietPlanWizardService();

  final RxBool loading = false.obs;
  final RxnString errorMessage = RxnString();
  final RxList<WizardDayGroupV2> weekDays = <WizardDayGroupV2>[].obs;

  // Which single day-group card is mid-request, if any - lets only that
  // one card's "Auto Adjust" button show a spinner instead of the whole
  // list (unlike `loading`, which covers the initial/whole-week load).
  final RxnString balancingDayPlanId = RxnString();

  // One-shot guard: only the step's initial load triggers auto-balance, not
  // any later loadWeekPlanItems() call (e.g. from editIngredients/swapRecipe
  // refreshing after a manual edit) - manually editing an ingredient must
  // never silently re-balance the rest of the day out from under it.
  bool _autoBalancedOnce = false;

  String get patientId => wizard.patientId;
  String get dietPlanId => wizard.dietPlanId.value ?? '';
  int get week => wizard.targetWeek.value;

  /// Same source TargetsStepController writes to - a plain per-day calorie
  /// figure, not the per-slot mealDistribution split (auto-balance operates
  /// on a day/week total, see services/ingredientAutoBalanceService.js).
  double? get dailyCalorieTarget =>
      (wizard.patientsController.selectedCalorieStrategy['calorieBudget'] as num?)?.toDouble();

  @override
  void onInit() {
    super.onInit();
    if (dietPlanId.isNotEmpty) _loadAndAutoBalanceOnce();
  }

  /// Called when the dietician returns to this step after changing plan
  /// items back on Step 2 (add/remove/swap a recipe) - Generate's
  /// "Continue" button triggers this on the already-created controller
  /// instance. GetX's lazyPut keeps this controller alive for the whole
  /// wizard session, so onInit's initial load/auto-balance above only ever
  /// runs once on its own - without this, removing a recipe on Step 2 left
  /// Step 3 showing the stale plan (including the removed item) with
  /// portions balanced against a calorie total that no longer matches.
  Future<void> refreshForReentry() async {
    _autoBalancedOnce = false;
    await _loadAndAutoBalanceOnce();
  }

  Future<void> _loadAndAutoBalanceOnce() async {
    await loadWeekPlanItems();
    final target = dailyCalorieTarget;
    if (!_autoBalancedOnce && target != null && target > 0 && weekDays.isNotEmpty) {
      _autoBalancedOnce = true;
      await autoBalanceWholePlan();
    }
  }

  Future<void> loadWeekPlanItems() async {
    loading.value = true;
    errorMessage.value = null;
    try {
      final response = await wizardService.getWeekPlanItems(patientId: patientId, dietPlanId: dietPlanId, week: week);
      if (response == null || response['success'] != true) {
        errorMessage.value = 'Could not load this week\'s plan.';
        return;
      }
      final data = response['data'] as Map<String, dynamic>;
      weekDays.assignAll((data['days'] as List? ?? []).map((d) => WizardDayGroupV2.fromJson(d)).toList());
    } finally {
      loading.value = false;
    }
  }

  /// "Edited" badge on a manually-portioned recipe card tapping through to
  /// unpin - returns the item to the pool that "Auto Adjust" rescales. The
  /// backend pins an item automatically whenever a portion edit is saved
  /// (see editIngredients); this is the only way to undo that. Does not
  /// change any portion.
  Future<void> unpin(WizardPlanItemV2 item) async {
    final result = await wizardService.setPinned(
      patientId: patientId,
      dietPlanId: dietPlanId,
      planItemId: item.id,
      pinned: false,
    );
    if (result != null && result['success'] == true) await loadWeekPlanItems();
  }

  Future<bool> editIngredients(WizardPlanItemV2 item, List<WizardIngredientLine> updatedIngredients) async {
    final result = await wizardService.createCustomVersion(
      patientId: patientId,
      dietPlanId: dietPlanId,
      planItemId: item.id,
      ingredients: updatedIngredients.map((i) => i.toJson()).toList(),
    );
    final ok = result != null && result['success'] == true;
    if (ok) await loadWeekPlanItems();
    return ok;
  }

  /// Re-balances just this one day's unlocked items toward the daily
  /// calorie target - the scoped-down "Auto Adjust" action on each day
  /// card, for after a manual ingredient edit throws that day's total off
  /// without wanting to touch every other day in the week (unlike the
  /// one-shot whole-week auto-balance on this step's initial load).
  Future<void> autoBalanceDay(WizardDayGroupV2 day) async {
    final target = dailyCalorieTarget;
    final dayPlanId = day.dayPlanId;
    if (target == null || target <= 0 || dayPlanId == null || dayPlanId.isEmpty) return;
    balancingDayPlanId.value = dayPlanId;
    try {
      final result = await wizardService.autoBalanceDay(
        patientId: patientId,
        dietPlanId: dietPlanId,
        dayPlanId: dayPlanId,
        targetDailyCalories: target,
      );
      if (result != null && result['success'] == true) await loadWeekPlanItems();
    } finally {
      balancingDayPlanId.value = null;
    }
  }

  /// One-shot entry balance: covers EVERY generated week of the plan, not
  /// just the one this step's UI shows. A Silver-tier plan generates all 4
  /// weeks up front (generation_step_controller.dart's _initialWeeksForTier)
  /// and finalize validates the whole plan - balancing only [week] here left
  /// weeks 2-4 at raw portions and blocked activation with "N day(s) outside
  /// +/-5% tolerance". Weeks other than [week] are balanced silently; the
  /// dietician still reviews/tweaks [week]'s day-groups in the list below.
  Future<void> autoBalanceWholePlan() async {
    final target = dailyCalorieTarget;
    if (target == null || target <= 0) return;
    loading.value = true;
    try {
      final result = await wizardService.autoBalancePlan(
        patientId: patientId,
        dietPlanId: dietPlanId,
        targetDailyCalories: target,
      );
      if (result != null && result['success'] == true) await loadWeekPlanItems();
    } finally {
      loading.value = false;
    }
  }

  /// "Total Budget" summary for one day-group - Selected Calories (summed
  /// across every non-linked item in that day, matching
  /// select_diet_sheet.dart's own per-day-group totals convention) vs
  /// Required Calories (the same dailyCalorieTarget auto-balance targets).
  double dayGroupSelectedCalories(WizardDayGroupV2 day) {
    var total = 0.0;
    for (final meal in day.meals) {
      for (final item in meal.items) {
        total += item.calories ?? 0;
      }
    }
    return total;
  }

  Future<void> swapRecipe(WizardPlanItemV2 item, String newParentRecipeId) async {
    final result = await wizardService.swapRecipeVersion(
      patientId: patientId,
      dietPlanId: dietPlanId,
      planItemId: item.id,
      newParentRecipeId: newParentRecipeId,
    );
    if (result != null && result['success'] == true) {
      await loadWeekPlanItems();
    } else {
      // Surface a backend rejection (e.g. a recipe with unresolved
      // ingredients - 404 with a message) instead of silently doing nothing.
      _showSwapError(result);
    }
  }

  void _showSwapError(dynamic result) {
    final ctx = Get.overlayContext;
    if (ctx == null) return;
    final message = (result is Map && result['message'] is String && (result['message'] as String).trim().isNotEmpty)
        ? result['message'] as String
        : 'Could not swap that recipe.';
    showAppToast(ctx, message: message, type: AppToastType.warning);
  }

  /// "Update Existing" on the Ingredient Editor's "Recipe Details" sheet -
  /// applies an AI-regenerated recipe (see recipe_details.dart's "Update AI
  /// Inputs") to just this one plan item, without touching the shared
  /// catalog recipe every other patient/plan pointed at [item]'s
  /// parentRecipeId still uses (that's what "Save as New Recipe" avoids too,
  /// by forking into a brand-new Recipe instead - this instead versions the
  /// existing one, scoped to this item only).
  Future<bool> updateItemFromRecipeSnapshot(WizardPlanItemV2 item, RecipePreview recipe) async {
    final result = await wizardService.updateItemRecipeVersion(
      patientId: patientId,
      dietPlanId: dietPlanId,
      planItemId: item.id,
      recipe: {
        'name': recipe.name,
        'ingredients': recipe.ingredients
            .map((i) => {'name': i.name, 'quantity': i.quantity, 'unit': i.unit})
            .toList(),
        'cookingSteps': recipe.cookingSteps,
        'components': recipe.components.map((c) => c.toJson()).toList(),
      },
    );
    final ok = result != null && result['success'] == true;
    if (ok) await loadWeekPlanItems();
    return ok;
  }
}
